### ISSUE TITLE
Changing Rewards

### ISSUE THREAD

**Issue by team-daniel** [jjshoots/PyFlyt#23]
I am using the QuadX-Waypoints env but want to scale the rewards, only the waypoint reached and crashed rewards. I downloaded the simulation through PyPi.

Can you tell me how to do this, do I call a specific variable? I can't quite figure it out.

Thanks  :)

**Comment by jjshoots** [comment]
I'm afraid that's not doable through the PyPI package. If you want to modify the rewards, you'll have to install from source:
1. Clone the repo using git clone.
2. Modify the reward structure in `PyFlyt/gym_envs/quadx_envs/quadx_waypoints_env.py` on line 152.
3. While in the repo, do `pip3 install -e .`.

Alternatively, you could use Gymnasium's reward wrapper to apply a custom function to the reward: https://gymnasium.farama.org/api/wrappers/reward_wrappers/#available-reward-wrappers

Let me know if this helps. :)
