### ISSUE TITLE
Insights in Published Results

### ISSUE THREAD

**Issue by team-daniel** [jjshoots/PyFlyt#24]
Hi, 

Thank you for your previous answer, it was very helpful.

I am looking to _hopefully_ use this **great** simulation to test a new RL method of my own. In your published paper, you reference some results of different algorithms w/ different reward structures on different envs. (See below)

For example, it would be useful to see the architecture, training params for the SAC-Dense model.

![Screenshot from 2024-02-18 11-16-14](https://github.com/jjshoots/PyFlyt/assets/55928249/5be86a1c-8934-42f1-bf7c-8375ae6bfd65)

I was wondering if you had any openly available code/repo that shows how you trained these agents, as information regarding architecture, training params, etc. is limited. I would love to have a look at the code for this. 

Many thanks, :)
Dan

**Comment by jjshoots** [comment]
Thanks! Looking forward to see what you do with it. The training code is here: https://github.com/jjshoots/E2SAC/tree/ccge2_pyflyt

It starts from src/main.py. Unfortunately the code is pretty messy, but do let me know if you need any help navigating it. :)
