### ISSUE TITLE
Sim-to-Real transfer

### ISSUE THREAD

**Issue by RibhavOjha** [jjshoots/PyFlyt#26]
Hi

In https://pypi.org/project/PyFlyt/0.3.0/#simulation-or-hardware
It is mentioned that PyFlyt provides a way for a sim-real transfer. However, i cannot find it in github repo. Please let me know how I can find it. 

![image](https://github.com/jjshoots/PyFlyt/assets/98718330/aa7292eb-7628-477f-a215-8873a6ad1bf6)

**Comment by jjshoots** [comment]
Hi! That was for PyFlyt 0.3, the current version is 0.16. The components for crazyflie usage have been migrated out into the CrazyFlyt library, with the script you are looking for being [here](https://github.com/jjshoots/CrazyFlyt/blob/master/examples/sim_n_fly_single.py).
