### ISSUE TITLE
Flight Modes documentation

### ISSUE THREAD

**Issue by mchawa** [jjshoots/PyFlyt#30]
I plan to write a detailed documentation explaining each of the flight mode.

Do you have any preferred way to add this documentation ?

Thanks.

**Comment by jjshoots** [comment]
You can update it [here](https://taijunjet.com/PyFlyt/documentation/core/drones/quadx.html#PyFlyt.core.drones.QuadX.set_mode). Modify the docstring of that function, then rebuild the docs under `docs_source`. Thanks!
