### ISSUE TITLE
Observation space with FlattenWaypointEnv

### ISSUE THREAD

**Issue by kbys-t** [jjshoots/PyFlyt#46]
I think shape should be (self.attitude_shape + self.context_length * self.target_shape,)
https://github.com/jjshoots/PyFlyt/blob/b985131be4ef69ff80d9a38fc4e7a1bf6763dbe5/PyFlyt/gym_envs/utils/flatten_waypoint_env.py#L35

**Comment by jjshoots** [comment]
Yep, you're right, would you be open to creating a PR for this? Otherwise I'll get to it later today. Thanks for the report!

**Comment by jjshoots** [comment]
The library has been fixed, installing 0.22.1 should work.
