### ISSUE TITLE
Quad Pole Balaning -> External Camera

### ISSUE THREAD

**Issue by defrag-bambino** [jjshoots/PyFlyt#50]
Hi,
for the QuadX Pole Balancing task I think it would make more sense to have an external camera, as in the fixedwing envs.

Thanks

**Comment by jjshoots** [comment]
Sure! That can be done. It's a very new env so any feedback is appreciated. Pole Waypoints has not officially been released yet.

**Comment by jjshoots** [comment]
Added in v0.24.0.
