### ISSUE TITLE
request to share one reinforcement learning example 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [jjshoots/PyFlyt#55]
Hello @jjshoots 

Thank you for sharing amazing and up to date PyBullet based crazyflie repository. It is really impressive work. I have a favor to ask. Could you please share some RL example? 

Many thanks.

**Comment by jjshoots** [comment]
Sure! Here's my current working setup: https://github.com/jjshoots/RLTeamAerialCombat/blob/main/src/vec_env_main.py

That said, if you're using the gymnasium environments, I would highly recommend something more standard like CleanRL.

**Comment by abdul-mannan-khan** [comment]
Thank you very much @jjshoots. I am really grateful to you for recommending me CleanRL.
