### ISSUE TITLE
[BUG] Dense reward not applied correctly in QuadXHover environment

### ISSUE THREAD

**Issue by rickstaa** [jjshoots/PyFlyt#7]
I think the dense reward is not applied correctly in the [QuadXHover](https://github.com/jjshoots/PyFlyt/blob/master/PyFlyt/gym_envs/quadx_envs/quadx_hover_env.py) environment:

https://github.com/jjshoots/PyFlyt/blob/0b4e89550680c153d8650ada6f6a58362c60f579/PyFlyt/gym_envs/quadx_envs/quadx_hover_env.py#L101C9-L110

According to the paper, the Euclidian and angle difference should be applied when the user sets `sprase_reward` to `False`. I created https://github.com/jjshoots/PyFlyt/pull/6 to fix this. This problem doesn't seem to exist in other environments.

**Comment by jjshoots** [comment]
Hi! Thank you so much for the catch!
